version: "3.7"
services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      args:
        user: dima
        uid: 1000
      context: ./
    image: laravel_8
    container_name: laravel_8-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
    networks:
      - laravel_8

  db:
    image: mysql:5.7
    container_name: laravel_8-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - laravel_8

  nginx:
    image: nginx:alpine
    container_name: laravel_8-nginx
    restart: unless-stopped
    ports:
      - "4545:80"
    volumes:
      - ./src/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel_8

networks:
  laravel_8:
    driver: bridge